# Generated by Django 5.2.8 on 2026-02-03 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('verifications', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='passportverification',
            name='date_of_birth',
            field=models.DateField(default='1996-05-15'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='passportverification',
            name='last_name',
            field=models.CharField(default='jane', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='passportverification',
            name='provider_response',
            field=models.JSONField(blank=True, help_text='Raw response from Interswitch for audit/debugging', null=True),
        ),
    ]
